### ISSUE TITLE
ERROR: invalid airspace class:    In OpenAir file for Austria from AustroControl

### ISSUE THREAD

**Issue by SchwarzwaldFalke** [BartVandewoestyne/oaconvert#129]
I tried to convert the 2015 open air data from austro control and got the following error message:

./oaconvert -o my_output.kml ../openair/austria/Openair/Austria_Airspace_2015_04.txt 
ERROR: invalid airspace class: 

Any idea?

This is the file:
https://gist.github.com/SchwarzwaldFalke/9e7efd74b2f6f5f7b606

It's from https://www.austrocontrol.at/piloten/vor_dem_flug/aim_produkte/luftraumstruktur_5

**Comment by Renevandenbroek** [comment]
I think it is the undifined airspace in a lot of the definitions in the file. In those cases there is only a blank after the airspace class "AC   "

**Comment by BartVandewoestyne** [comment]
This is not a bug in oaconvert.  Your Open Air file has "AC"-records where no airspace class is specified.  According to the 'most official' Open Air specification at http://www.winpilot.com/usersguide/userairspace.asp, an "AC"-record must have an associated airspace class.  So the solution to your problem is to decide what airspace class the airspaces should belong to, and fix the empty "AC"-records.  Once you've done that, you might also inform the people who are providing those airspace files that they have errors in their files.
