### ISSUE TITLE
Airspace TRA "Temporary reserved airspaces" missing

### ISSUE THREAD

**Issue by SchwarzwaldFalke** [BartVandewoestyne/oaconvert#130]
I just digged a bit deeper into oaconvert today.
As far I have seen the airspace class "TRA" is missing. It's at least used in austria.
Definition (Point 1.4.1):
http://eaip.austrocontrol.at/lo/150306/PART_2/LO_ENR_2_2_en.pdf 

So a TRA would need the AL and AH (more important AH) value inside the Polish Label, because you are allowed to fly inside the TRA. Is this possible with oaconvert?

**Comment by BartVandewoestyne** [comment]
In Belgium, we have similar "Temporary Reserved Airspaces" or "Temporary Reserved Areas".  These fall under airspace class 'R' (Restricted) and in an Open Air file are typically encoded in a way similar to this:

    AC R
    AN TRA Foo Bar
    AH <upper limit>
    AL <lower limit>
    ... coordinates follow here ...

See for example the files

    tra23_tienen_area.txt
    tra_south_alpha.txt
    tra_tsa_s1_namur_area.txt
    tra_tsa_s4_charleroi_area.txt

in the `openair/belgium` directory.

If you confirm that this is an acceptable solution for your problem, then please let me know so I can close this issue.

**Comment by SchwarzwaldFalke** [comment]
Hi,

as far as I understand there is a difference between these two.
In Austria if the TRA is active, your are allowed to fly into these area. Because of this the Open Air entry looks like this:

AC G
AN TRA HOLZLEITENSATTEL 1
AL 7000ft msl
AH 9500ft msl
DP 47:18:54 N 010:53:15 E
DP 47:18:58 N 010:55:20 E
DP 47:17:26 N 010:53:04 E
DP 47:16:56 N 010:52:51 E
DP 47:16:59 N 010:52:32 E
DP 47:17:52 N 010:52:28 E
DP 47:18:54 N 010:53:15 E

So it's airspace G if it's active. Because of this it would be nice to have AH and AL in the polish label.

**Comment by SkipAir** [comment]
Hi,

You're situation with the TRA within military airspace, is very similar to our LFA G.
https://github.com/BartVandewoestyne/oaconvert/blob/master/openair/belgium/low_flying_area_golf2_south.txt

I understand your request as when class G airspace is encountered, text for the naming of the area in the polish format also includes the AH altitude, .eg.
"1524m max (LFA G1)" instead of "LFA G1" as it is currently the case.

Is this correct?

**Comment by SkipAir** [comment]
If the TRA is a TRA where gliders are allowed, I would recommend using one of the following:
- AN TRA <name>
- AC G or W
And inverse the activation rule, that is: when active, deactivate it in your instrument.

If the area is cutting a piece out of bigger area, you need to split up the bigger one, so that you can deactivate this part in your instrument.

For information: have a look at my last comment in the following issue:
https://github.com/BartVandewoestyne/oaconvert/issues/145
