### ISSUE TITLE
Consider support for abbreviations from New Zealand's AIP

### ISSUE THREAD

**Issue by BartVandewoestyne** [BartVandewoestyne/oaconvert#145]
The AIP for New Zealand (http://www.aip.net.nz/) uses the following abbreviations:

MBZ: Mandatory Broadcast Zone
CFZ: Common Frequency Zone
VHZ: Volcanic Hazard Zone
LFZ: Low Flying Zone
GAA: General Aviation Area

which oaconvert currently does not support.  Icao Document 8400 does not mention these.  We should decide what to do:

* Option 1: categorize these zones under one of the official airspace classes and not change oaconvert (New Zealand's OpenAir files will have to be adapted).
* Option 2: add support for these types of airspaces in oaconvert.

Furthermore, the interpretation for LFA (Low Flying Area) in New Zealand might be different from the one in Europe.  European LFA might be equivalent to New Zealand's GAA (a part of class C/D airspace that can be opened up as class G at certain times) (check!).  An LFA in New Zealand is where you are allowed to fly from ground to 500ft.  We should check this and decide what to do.

**Comment by SkipAir** [comment]
The main issue is that fact that the OpenAir standard is crap, because:
1. it's not well defined (leaves too many things undefinded, such as altitude units etc.)
2. it's not at all in phase with the ICAO classifications of airspace.

At the same time the ICAO airspace classifications are quite confusing also, because airspaces such as CTR, TMA, TCA, LCA have a class (A, B, C, D, E, F, G) clearly defining if VFR traffic is allowed (linked to the principle of traffic seperation between IFR and VFR), but others such as TSA/TRA, Prohibited, Danger, Restricted, LFA etc. don't. For the latter type of airspaces, usually the "nature of restriction / type of hazard" for the area will be written in the AIP with footnotes giving more detail. It is then up to a personal judgement of the pilot to decide how to deal with the information.

In my opinion, since we are using the OpenAir format because we want to download it in our GPS, we need to stick to the format with its limitations. As such, we need to define ourselves a mapping between the airspace definition from the AIP and the airspace classes (AC) available in the OpenAir standard. 

Personally, I believe that the most correct interpretation is that many of these special areas such the ones mentioned above (LFA, LFZ, MBZ ...) fall into the OpenAir class "AC R" (Restricted). It is then the type of restriction that will determine which aircrafts are allowed into the airspace and which are not.

From a more practical point of view, I tend to define all the airspaces in which I'm allowed to fly under the OpenAir class "AC Q" (Danger), and the ones in which I'm not allowed to fly under "AC R" (Restricted). In that case, I basically can skip the download of all the Danger zones (I just need to be aware of them during flying). Even though this approach is very convenient for flying, it is very questionable, because:
1. it assumes a specific type of aircraft
2. it is open to personal interpretation
E.g. legally a sailplane is allowed to fly into an LFA or LFZ area, however, in Belgium and France these areas are used for very low altitude, high performance flights with fighter jets, hence I prefer to stay clear of them and have them in my GPS as "Restricted".

A shocking example is for instance the Belgium area EBD20:
nature of restriction / type of hazard = Gunnery area.
but the area is from GND up to FL140
Without having additional information, I can only come to the conclusion this military area is used for ground-to-air missile exercises and this means I want to stay out of it when it is active, even though that legally, since it is a danger zone, I can enter the area! The dilemma is then: do I put it under "AC Q" with the risk that other paragliding pilots omit this area in their GPS, or do I put it under "AC R" because I assume it's dangerous.

**Comment by SkipAir** [comment]
In conclusion: I recomend to stick the the OpenAir classes (AC), that is
* AC class    ;    class = Airspace Class, see below:
*     R restricted
*     Q danger
*     P prohibited
*     A Class A
*     B Class B
*     C Class C
*     D Class D
*     GP glider prohibited
*     CTR CTR
*     W Wave Window
and put the airspace type abbreviation (LFA, TSA etc.) in the airspace name (AN)
with 2 exceptions:
1. also use class "AC E, F, G" for class ICOA class E, F, G areas
2. omit the class "AC CTR" because a CTR can still be ICAO class A, B, C, D, E
knowing that all class E, F, G and Q areas can be used for flight prepartion purposes, but are usually omitted by pilots when downloading into their instrument.

**Comment by BartVandewoestyne** [comment]
I agree with sticking to the OpenAir classes as defined online at http://www.winpilot.com/usersguide/userairspace.asp  However, I do *not* agree with omitting the CTR class.  First of all, it is an official OpenAir airspace class.  Secondly, oaconvert allows the specification of multiple airspace classes (separate them with forward slashes and without spaces in between), for example

AC CTR/E

would be a CTR that has ICAO class E.  Would that be an acceptable solution?

**Comment by SkipAir** [comment]
The OpenAir standard is badly written. It only has one AC field and it confuses 2 types of information:
- the class: only related to control and seperation of traffic in a specific area
- the type of an area: CTR, TMA, TRA, TSA, TMZ, etc.

The same goes for the "AC W" class, which is basically a "private" class G like the Belgian MILFAG (Military LFA G), a piece of military airspace that is given to sailplane gliders under certain restrictions. Here also, one can question what the class should be. Because there is no seperation of traffic (minimum distances etc.), the class is by definition G. This is important, because it means a sailplane can be right at the border. Hence if the airspace above is for instance C, an controlled airplane needs to maintain 500ft margin to this border. 
However, because there are restrictions (prior clearance before entering + radio contact + prior signature of the "Letter of Agreement") one could see this as class R (restricted).

A consistent approach is required. If you decide to use "AC CTR/E", logically, you should also use "AC TMA/C" etc.which is then not allowed according the OpenAir standard ... hence my proposal to just avoid using the "AC CTR" class in OpenAir and use the following naming convention in the AN field:
- XXXX-<type> <description>
when it is specifically linked (controlled by an AD)
E.g. EBFS-CTR Liege, EBFS-TMA Liege, EBLG-TMA1 Liege, EBLG-TMA2 Liege
- XX-<type> <description> or XX-<type>-<nr> <description> in other cases
E.g.: EB-TSA26-A Ardennes 01, EB-TSA26-B Ardennes 02, 
EB-LFAG2-S LFA G2 South, EB-LFAG5-W, LF-R45-N2 ...

This way, we respect the OpenAir format as it is defined, but we give all necessary information to the pilotes, who can read the AN on their instruments.

This is also more consistant with NOTAM information such and makes it easier to recongnize and assigne automatically airspace areas to NOTAM Activation (ACT) messages

Another issue is that I don't know how our instruments will deal with the special character "/".
This needs to be tested first.
