### ISSUE TITLE
Useldange glider box and corridor

### ISSUE THREAD

**Issue by BartVandewoestyne** [BartVandewoestyne/oaconvert#68]
The AH and AL are currently set to the same value by Wim for some reason that still needs to be discussed...  Discuss this issue and fix it.

**Comment by SkipAir** [comment]
The idea of setting AH and AL to the same came from the fact that the Garmin map only shows the AL atlitude, and that since sailplanes are allowed to fly into these areas, they are allowed to go up to the AH value. 

However, more and more flying instruments are supporting directly the OpenAir format with in-flight horizontal **and vertical** distance check and warning. Hence the strategy should evolve. Wave (sailplane) areas, should bacically be defined as controlled airspace that can be switched off (or removed from the OpenAir file on the instrument) when clearance is obtained. If the area is cutting a piece out of bigger area, you need to split up the bigger one, so that this specific part can be deactivated in the instrument.

These areas are glider areas with very specific restrictions (radio contact, transponder and prior AD clearance). 

I would recommend using one of the following:
- AN TRA
- AC W with inversed activation rule, that is: when active, deactivate it in your instrument.
- AH <as defined in AIP>
- AL <as defined in AIP>

For information can be found in my last comment in the following issue:
https://github.com/BartVandewoestyne/oaconvert/issues/145
